<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNqObw4u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNqObw4u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNqObw4u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNqObw4u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNqObw4u\App_KernelDevDebugContainer([
    'container.build_hash' => 'NqObw4u',
    'container.build_id' => '4d908324',
    'container.build_time' => 1762526781,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNqObw4u');
