<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGfzeQnD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGfzeQnD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGfzeQnD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGfzeQnD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGfzeQnD\App_KernelDevDebugContainer([
    'container.build_hash' => 'GfzeQnD',
    'container.build_id' => 'd0aa822b',
    'container.build_time' => 1762523590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGfzeQnD');
