<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP0m5Y79\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP0m5Y79/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP0m5Y79.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP0m5Y79\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP0m5Y79\App_KernelDevDebugContainer([
    'container.build_hash' => 'P0m5Y79',
    'container.build_id' => '50ce2c95',
    'container.build_time' => 1762520076,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP0m5Y79');
